spring:
  profiles:
    active: dev

  datasource:
    url: ${env.mysql.url}
    username: ${env.mysql.username}
    password: ${env.mysql.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 3
      validation-query: select 1
      max-total: 20
      max-wait-millis: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      max-open-prepared-statements: 20
      pool-prepared-statements: true
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      min-idle: 1
      initial-size: 2

  redis:
    host: ${redis.host}
    port: ${redis.port}
    timeout: "500"
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: "200"
        max-idle: 8
        min-idle: 2

  thymeleaf:
    cache: false

  dubbo:
    application:
      name: consumer
    registry:
      address: zookeeper://139.199.65.244:2181
    scan: com.magotzis.dm.api.service

mybatis:
  type-aliases-package: com.magotzis.dm.model
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081